spring:
  datasource:
    url: jdbc:h2:mem:test
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  flyway:
    url: jdbc:h2:mem:test
    user: sa
   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 500KB
      max-request-size: 500KB

  output:
    ansi:
      enabled: always

server:
  error:
    include-message: always
    
app:

  access-token-expiration-ms: '#{1000 * 30}' # 30 секунд
  
  refresh-token-expiration-ms: '#{1000 * 60}' # 1 минут
  
  
# '#{1000 * 60 * 15}'  15 минут

# '#{1000 * 60 * 60 * 60 * 24 * 15}' # 15 дней
  
      
      
     