spring:
  datasource:
    url: jdbc:h2:mem:test
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  flyway:
    url: jdbc:h2:mem:test
    user: sa
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  output:
    ansi:
      enabled: always

server:
  error:
    include-message: always
    
app:

  access-token-expiration-ms: '#{${ACCESS_TOKEN_EXPIRATION_MS:1000 * 30}}' # 30 секунд
  
  refresh-token-expiration-ms: '#{${REFRESH_TOKEN_EXPIRATION_MS:1000 * 60}}' # 1 минут